language: java
addons:
  sonarcloud:
    organization: erikwiklander-github
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: "tJoB7u6tgmkoXqdHlZK3cEANjmpQknyvN5ZA0tWLqPVFav/b6Srrr5MsqSh2lCQtb9TU6TwJ0mqGQfMd4+C+r2WuTBYkGxVl1W79qqYU+ckHGh65ZWDB7hO8k/L3ezz/k+RoFXKZPdjmF480+ctPyQqstz0JyDrIHqOK3c1HxgWe/k8+I8hlVTdFwXxhUNELw7yFlMlA81yodkY2c5LaCSkwivfxVt0L38yWeMSDBLZpG2xiCQA2HwJWOPweVqCYmOHINaAGm4RLIEGGvq0tMjsIbNbYnKie85CmUH2qrsRGdDvKG8BfkhKSJ1l37tJWjCKiCkeHhEAcuUZIq6xXgGhkgYYiCF9A7m/jl7XCEOiHML/IMZYhHdpGgf+nFmjl4enqp+5wrEqJ9z3dm90tPiKafdffienqU3G76F6Epbn79z1yhR2kgpMW3vUrcNX1haRjcdqQmRDm8peJKBotHSLCnE9E5dCmqmFpX4wJS2GsTXsx28g0gneem/9V/+LNz9JGmrj9lulD5hUZyhXcZuFvcmtBu5hk0V2KEaDMiCTUwMUXXr/gHd+xkyo1pEStNBKLb94Xk829Ry0aBtS8lv1yIfrSu9jW0YF1791oHgUTtGCTDrh4NIiXw7NN+HDqFDm+Dor7bZt9ctNWCfEab9tDmtqsoi7cRW8IkjgWA6g="
  app: griffin-flex
  on:
    repo: erikwiklander/flex
