language: java
addons:
  sonarcloud:
    organization: erikwiklander-github
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  app: griffin-flex
