language: java
addons:
  sonarcloud:
    organization: erikwiklander-github
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: ssrHtaP7s3qese0q6McJs6pb7CR+frf48OvFTNhuBrtNbG2tr9DrcgiANppZNSpCkGeG8gUnCgR6JiZ1ztL0kgNwSVm7/AkMGcf2Sb5dQuAvRvTxmlHcO5eioOG83H2qgy5MxggZ3Vwv1X2ktkSMWjd7XkVuXvGdDaJcpf+SOpLuc76QWwfaBTudRK5etHc2+UXuw6K4fnDMJCRNINaM6vuhqRc8TZ/m+kf0v0THqbdv4zeL6v/yhf9WcTgyuI/cB9hrWp8sNsEv6/TwMkysL3jzW6bf//OzPbj3ZJDPJShL2ao/f3GFcXGFygqgFwfrhrN0ySisuKDY3kKT544JdUX/pFewXWb3VpbNi8eR0dQThyDoAEVb+7sj4f23TxV57vEXwRr8MmZguU5UxktxqteLqOAPhSdBVu8w7gogeHBfXfVyQGx8cNUX5+BGFP79iF2CMq4HN+CXuUXb9lTJdeqywwbOAG+8lqEStGYXBWYOiS+sAtrmhkXZrnVdXB+C561In5A398kiFbfsORHyb84i61eYlUqxNhdyMeZegyLfQAoR7tWC9zqC4Tzj4nyyyV9LbCp2pMbkXCFO2R+O4SJ6VJyzIsro/GDzTKNA6WBpIUSwaess+VLiwpx8pEbwMrh+X3lDv5vLF+ionFZNhLutnZeafG41vb9TFPQ9uR4=
  app: griffin-flex
